name: Ahnp Push Check
on:
  push:
    branches:
      - master

jobs:
  commit-check:
    name: Code Validation Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: dart-lang/setup-dart@v1

      - name: Install Doc Generator
        run: dart pub global activate dartdoc

      - name: Getting Checked In Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: dart pub get

      - name: Generate Code
        run: dart pub run build_runner build --delete-conflicting-outputs

      - name: Check Code Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Source Code
        run: dart analyze

      - name: Run tests
        run: dart test --debug --test-randomize-ordering-seed random --concurrency=30 --reporter=expanded

      - name: Generating Package Docs
        run: dartdoc

      - name: Pushishing Package Docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: doc/api 